### PR TITLE
Add `--filter` flag, and make binary `go install`-able

### PR DESCRIPTION
**Pull request by matthew-healy**
This PR adds a `--filter` option, giving users more fine-grained control over which files actually get included in the archived library.

It also makes it possible to run `go install github.com/cloudsmith-io/gopack` to have the `gopack` binary installed on your system (which, in my use case, makes it significantly easier to use `gopack` in CI).

Finally, I replaced the `github.com/rogpeppe/go-internal` library with the official `golang.org/x/mod` one.

(If you'd prefer, I can also submit these changes as separate PRs - just let me know!)

### CODE REVIEW

**Comment by matthew-healy** [comment]
@paddycarey - Hi! Just wanted to confirm that you saw this PR & someone will be taking a look at some point.

There's no major rush, but thought I'd check in as it's been open for a week. :smile:

**Comment by paddycarey** [comment]
Hi @matthew-healy, yep it's on the list! It's been a busy week here but should be able to get this reviewed and shipped tomorrow I hope.

**Comment by matthew-healy** [comment]
Amazing, thank you! :pray:

**Review by paddycarey — APPROVED** [review]
LGTM! Sorry for the delay here @matthew-healy 🙈

**Comment by paddycarey** [comment]
Took a little back and forth to get goreleaser working again, but this change should be available in https://github.com/cloudsmith-io/gopack/releases/tag/v0.6.0

**Comment by matthew-healy** [comment]
Thanks @paddycarey!

**Pull request merged**
